# Subchart configurations
# Configure installation, image, and node selector for each service

cloudnative-pg:
  enabled: true
  # -- Specifies whether the CRDs should be created when installing the chart.
  crds:
    create: true
  image:
    repository: ghcr.io/cloudnative-pg/cloudnative-pg
    tag: 1.28.1
  nodeSelector: {}
  # Example:
  # nodeSelector:
  #   role: database
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

strimzi-kafka-operator:
  enabled: true
  image:
    registry: quay.io
    repository: strimzi
    name: operator
    tag: 0.51.0
  nodeSelector: {}
  # Example:
  # nodeSelector:
  #   role: kafka-operator
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault


# Readiness check job configuration
waitJob:
  image:
    repository: bitnami/kubectl
    tag: latest

openebs:
  enabled: true
  localpv-provisioner:
    enabled: true
    # Hostpath settings matching our Talos setup
    hostpath:
      basePath: /var/local/openebs

  # Enabling NDM for Raw Disk /dev/sdb discovery
  ndm:
    enabled: true
    sparse:
      enabled: false # Disable sparse files, use real disks
  
  ndmOperator:
    enabled: true

  # Enable the Local Device provisioner to use the discovered block devices
  localpv-device:
    enabled: true

  # Security Context and Mounts for Talos (NDM Workers)
  # Allowing NDM to scan host devices /dev, /sys and /run/udev
  ndm-config:
    filter-configs:
    - key: os-disk-exclude-filter
      name: os-disk-exclude-filter
      state: true
      value: "loop,fd0,sr0,ram,dm-,md"
    - key: vendor-filter
      name: vendor-filter
      state: true
      value: "Google,Amazon,Azure"
    - key: path-filter
      name: path-filter
      state: true
      value: "/dev/sda" # Exclude the OS disk
