# Subchart configurations
# Configure installation, image, and node selector for each service

cloudnative-pg:
  enabled: true
  # -- Specifies whether the CRDs should be created when installing the chart.
  crds:
    create: true
  image:
    repository: ghcr.io/cloudnative-pg/cloudnative-pg
    tag: 1.28.1
  nodeSelector: {}
  # Example:
  # nodeSelector:
  #   role: database
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

strimzi-kafka-operator:
  enabled: true
  image:
    registry: quay.io
    repository: strimzi
    name: operator
    tag: 0.51.0
  nodeSelector: {}
  # Example:
  # nodeSelector:
  #   role: kafka-operator
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault


# Readiness check job configuration
waitJob:
  image:
    repository: bitnami/kubectl
    tag: latest
