"""Change ID to String for alphanumeric IDs

Revision ID: 5658e9f8ee08
Revises: 6e5395af4202
Create Date: 2026-03-26 17:17:55.758607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5658e9f8ee08'
down_revision: Union[str, None] = '6e5395af4202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_instances', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=False,
                   autoincrement=False) # Important for PK switch
        batch_op.drop_index('ix_db_instances_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_db_instances_id'), 'db_instances', ['id'], unique=False)
    op.alter_column('db_instances', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
