apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infra-provisioner.fullname" . }}
  labels:
    {{- include "infra-provisioner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "infra-provisioner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "infra-provisioner.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.config.service_account_name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "infra-provisioner.fullname" . }}-config
          volumeMounts:
            - name: db-storage
              mountPath: /db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: db-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "infra-provisioner.fullname" . }}-db
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
